project_id = "ipvwbvzsjqitzrwpmysj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "https://dd3f156a-5ca0-42c6-a487-a071fa2dce7c.lovableproject.com"
additional_redirect_urls = ["https://dd3f156a-5ca0-42c6-a487-a071fa2dce7c.lovableproject.com"]

[storage]
enabled = true
file_size_limit = "50MiB"

[realtime]
enabled = true

[analytics]
enabled = true
port = 54327

[vector]
enabled = true
port = 54328

[functions]
enabled = true

[functions.google-maps-integration]
verify_jwt = true

[functions.background-check]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.confirm-payment]
verify_jwt = true